title : LitSarah

author :
  name : Sarah Little
  email : litsarah+github@gmail.com
  github : litsarah
  twitter : litsarah
  linkedin: litsarah

timezone: America/Chicago

gems:
    - jekyll-sitemap

highlighter: rouge
