title: Sarah Little
author: Sarah Little
email: litsarah+github@gmail.com
description: >
  A quality assurance engineer who works with developers, managers, and business owners to deliver data-driven solutions. Supports local and global teams in simplifying development, operations, and QA processes by providing reliable, easily accessible tools. Trained in Agile DevOps methodologies and software development lifecycles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://litsarah.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
twitter_username: litsarah
github_username: litsarah
linkedin_username: litsarah
webmentions_feed: https://webmention.io/api/mentions.html?token=qfElp_U_xg_w3nzWPsrmHw

# Build settings
plugins:
  - jekyll-feed
